hl.on("hyprland.start", function ()
   hl.exec_cmd("qs")
   hl.exec_cmd("hypridle")
   hl.exec_cmd("hyprsunset -t 6500")
   hl.exec_cmd("awww-daemon")
   hl.exec_cmd("systemctl --user start hyprpolkitagent")
   hl.exec_cmd("dbus-update-activation-environment --all")
   hl.exec_cmd("hyprctl setcursor Bibata-Modern-Classic 24")
   hl.exec_cmd("wl-paste --type text --watch cliphist store")
   hl.exec_cmd("wl-paste --type image --watch cliphist store")
end)